### PR TITLE
Feature/sagi edits

### PR DESCRIPTION
**Pull request by sagittaeri**
some edits, fix up some of my past embarrassing mistakes and bad writing.

### CODE REVIEW

**Comment by EchoFrost** [comment]
Looks good. Do we have a game-plan for communicating these and future edits to the voice actors? 
@TheForeverLoneWolf

**Comment by Wolf-GameDev** [comment]
@sagittaeri Make sure you write down the voice lines you modify! I'm the one managing VA reworks and I need to make sure that I don't miss anything when handing out lines :)

**Review by EchoFrost — APPROVED** [review]

**Comment by sagittaeri** [comment]
I marked it with "TODO VA:" in comments

**Comment by Wolf-GameDev** [comment]
Please also put it into a doc, that way we don't miss it.

**Comment by sagittaeri** [comment]
Is this an existing doc? Or are you hinting that I should make one? XD

**Comment by Wolf-GameDev** [comment]
Feel free to just put it into a blank one and I'll merge it with the one I'm planning on making myself.

**Comment by sagittaeri** [comment]
Here, use this:
[https://docs.google.com/spreadsheets/d/1kCCdOO6-u3o-HgM-8kBP2jJ-aeykPaKdFgEWwQ9DOpo/edit#gid=0](https://docs.google.com/spreadsheets/d/1kCCdOO6-u3o-HgM-8kBP2jJ-aeykPaKdFgEWwQ9DOpo/edit#gid=0)

**Pull request merged**
